name: Build and Test Go

on:
  pull_request:
    branches: [ "workflow" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build

